motracker/gpsdb/forms.py
# -*- coding: utf-8 -*-
"""User forms."""
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileRequired
from wtforms import BooleanField, FileField, StringField
from wtforms.validators import DataRequired, InputRequired

from motracker.extensions import filez


class ApiForm(FlaskForm):
    """Change API key form."""

    confirm = BooleanField(
        "If you want to generate a new key, please select this checkbox to confirm",
        validators=[InputRequired()],
    )

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(ApiForm, self).__init__(*args, **kwargs)
        # self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(ApiForm, self).validate()
        if not initial_validation:
            return False
        return True


class AddFileForm(FlaskForm):
    """Add GPX file."""

    description = StringField("GPX File Description", validators=[DataRequired()])
    is_private = BooleanField("Do you want to keep this file privately?")
    upload_file = FileField(
        "Chose File",
        # validators=[FileRequired(), FileAllowed(filez, 'GPX tracks onlY!')]
        validators=[FileRequired()],
    )

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(AddFileForm, self).__init__(*args, **kwargs)

    def validate(self):
        """Validate the form."""
        initial_validation = super(AddFileForm, self).validate()
        if not initial_validation:
            return False
        return True

motracker/gpsdb/__init__.py
# -*- coding: utf-8 -*-
"""The gpsdb module."""
from . import views  # noqa

motracker/gpsdb/views.py
# -*- coding: utf-8 -*-
"""Gpsdb views."""

import binascii
import gpxpy
import json
import pynmea2
import re
import redis
import strgen
import uuid
from datetime import datetime, date
from flask import (
    Blueprint,
    current_app,
    flash,
    jsonify,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from flask_login import current_user, login_required
from flask_mail import Message
from sqlalchemy import text

# from motracker.extensions import celery, db, filez
from motracker.extensions import csrf_protect, db, mail
from motracker.user.models import User
from motracker.utils import flash_errors, gpx2geo

from .forms import AddFileForm, ApiForm
from .models import ApiKey, Filez, Pointz, Trackz

# SUPPORT FUNCTIONS and CONSTANTS
# -------------------------------


# fake track as default response
faketrack = '{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":\
        "LineString","coordinates":[[102.0, 0.0], [103.0, 1.0], [104.0, 0.0], [105.0, 1.0]]}}]}'

# $RMC
def parse_rmc(gprmc):
    """Parsing NMEA-0183 $RMC record into more human set of values.

    Recommended Minimum Specific GPS/TRANSIT Data:
    parser library: https://github.com/Knio/pynmea2
    """
    valuez = pynmea2.parse(gprmc)

    lat = valuez.latitude
    lon = valuez.longitude
    speed = valuez.spd_over_grnd
    bearing = valuez.true_course
    timez = datetime.combine(valuez.datestamp, valuez.timestamp)
    trackdate = valuez.datestamp

    return dict(
        timez=timez, lat=lat, lon=lon, speed=speed, bearing=bearing, trackdate=trackdate
    )


###########
# MAIN PART
blueprint = Blueprint("gpsdb", __name__, url_prefix="", static_folder="../static")


@blueprint.route("/apikeys", methods=["GET", "POST"])
@login_required
def gpsapi():
    """(re)Generate and/or present API key."""
    form = ApiForm(request.form)
    hasapi = ApiKey.query.filter_by(user_id=current_user.get_id()).all()
    # Handle regeneration of API key
    if request.method == "POST":
        if form.validate_on_submit():
            apikey = strgen.StringGenerator("[\w\d]{10}").render()
            ApiKey.create(user_id=current_user.get_id(), apikey=apikey)
            db.session.commit()
            current_app.logger.info("API key has been added.")
            flash("API key {} has been added.".format(apikey), "info")
            return redirect(url_for("gpsdb.gpsapi"))
        else:
            flash_errors(form)
    # No regeneration request
    apikey = []
    if hasapi:
        for x in hasapi:
            apikey.append(x.apikey)
    db.session.close()
    return render_template("gpsdb/apikey.html", form=form, apikeys=apikey)


@blueprint.route("/apikeys/rm/<string:api>", methods=["GET"])
@login_required
def rmapi(api):
    """RM api key. Everyone logged can remove a key if known."""
    hasapi = ApiKey.query.filter_by(apikey=api).first_or_404(description='There is no data with api key {}'.format(api))
    print(hasapi.apikey)
    db.session.delete(hasapi)
    db.session.commit()
    flash("API key {} has been removed.".format(hasapi.apikey), "warning")
    return redirect(url_for("gpsdb.gpsapi"))


@blueprint.route("/gnss/files", methods=["GET", "POST"])
@login_required
def filezsave():
    """Upload previously recorded tracks."""
    form = AddFileForm()
    if request.method == "POST":
        if form.validate_on_submit():
            # Verify if the GPX is valid
            file = request.files["upload_file"]
            try:
                # At the moment we support UTF-8 files and compatible only
                rid = uuid.uuid4()
                parsedfile = file.stream.read().decode("utf-8")
                ourgpx = gpxpy.parse(parsedfile)
                # file is parsing, so we are extracting basic interesting data about it
                length_2d = ourgpx.length_2d()
                length_3d = ourgpx.length_3d()
                moving_time, stopped_time, moving_distance, stopped_distance, max_speed = (
                    ourgpx.get_moving_data()
                )
                uphill, downhill = ourgpx.get_uphill_downhill()
                start_time, end_time = ourgpx.get_time_bounds()
                points_no = len(list(ourgpx.walk(only_points=True)))
            except Exception as e:
                current_app.logger.info(e)
                flash("Uploaded file is not a valid GPX. Try another one.", "warning")
                query = Filez.query.filter_by(user_id=current_user.get_id()).all()
                return render_template("gpsdb/filez.html", allfilez=query, form=form)
            dbfile = Filez.create(
                user_id=current_user.get_id(),
                is_private=form.is_private.data,
                rid=rid,
                description=form.description.data,
            )
            # all tracks are saved with filename which is equal to database ID
            fname = current_app.config["UPLOADS_DEFAULT_DEST"] + str(rid) + ".gpx"
            with open(fname, "w", encoding="utf-8") as f:
                f.write(parsedfile)
            fname = current_app.config["UPLOADS_DEFAULT_DEST"] + str(rid) + ".txt"
            with open(fname, "w", encoding="utf-8") as f:
                try:
                    f.write("Number of points: {}\n".format(points_no))
                except Exception as e:
                    current_app.logger.debug(e)
                try:
                    f.write("Start time: {}\n".format(start_time))
                except Exception as e:
                    current_app.logger.debug(e)
                try:
                    f.write("End time: {}\n".format(end_time))
                except Exception as e:
                    current_app.logger.debug(e)
                try:
                    f.write("2D length: {}\n".format(length_2d))
                except Exception as e:
                    current_app.logger.debug(e)
                try:
                    f.write("3D length: {}\n".format(length_3d))
                except Exception as e:
                    current_app.logger.debug(e)
                try:
                    f.write("Moving time: {}\n".format(moving_time))
                except Exception as e:
                    current_app.logger.debug(e)
                try:
                    f.write("Stopped time: {}\n".format(stopped_time))
                except Exception as e:
                    current_app.logger.debug(e)
                try:
                    f.write("Moving distance: {}\n".format(moving_distance))
                except Exception as e:
                    current_app.logger.debug(e)
                try:
                    f.write("Stopped distance: {}\n".format(stopped_distance))
                except Exception as e:
                    current_app.logger.debug(e)
                try:
                    f.write("Max speed: {}\n".format(max_speed))
                except Exception as e:
                    current_app.logger.debug(e)
                try:
                    f.write("Uphill: {}\n".format(uphill))
                except Exception as e:
                    current_app.logger.debug(e)
                try:
                    f.write("Downhill: {}\n".format(downhill))
                except Exception as e:
                    current_app.logger.debug(e)
            flash("Successfully uploaded your GPX file.", "info")
            current_app.logger.debug("Saved File: " + str(rid) + ".gpx")
        else:
            flash_errors(form)
    # Present all files belonging to user
    query = Filez.query.filter_by(user_id=current_user.get_id()).all()
    current_app.logger.debug(query)
    gpxq = {}
    for x in query:
        # A brief description presentation
        fname = current_app.config["UPLOADS_DEFAULT_DEST"] + str(x.rid) + ".txt"
        with open(fname, "r", encoding="utf-8") as f:
            read_file = f.readlines()
            gpxq[x.id] = read_file
    return render_template("gpsdb/filez.html", allfilez=query, gpxq=gpxq, form=form)


@blueprint.route("/gnss/gpx/<string:gpx_rid>")
def gpxtrace(gpx_rid):
    """Initiates convertion of GPX into our DB and redirects to show GPX on a map."""
    # TODO: use celery to parse the track
    # check if we have the GPS already rendered, if not, render it
    rid = uuid.UUID(gpx_rid)
    track = Trackz.query.filter_by(gpx_rid=rid).first()
    if not track:
        # get username current user
        track_rid = gpx2geo(rid)
    else:
        track_rid = track.rid
    return redirect(url_for("gpsdb.showtrack", track_rid=str(track_rid)))


@blueprint.route("/gnss/tracks/<string:username>")
def usertracks(username):
    """Lists all tracks for the particular user."""
    # check if username was provided and is valid, else flask sends 404.
    if isinstance(username, str):
        # check if user exists
        userdb = User.query.filter_by(username=username).first_or_404()
        user_id = userdb.id
        # we do not list GPX static files here, only live tracks
        q1 = Trackz.query.filter_by(id=user_id, gpx_id=None).all()
        if q1:
            current_app.logger.debug(q1)
            return render_template("gpsdb/alltracks,html", username=username)
        else:
            return render_template("404.html"), 404


@blueprint.route("/gnss/show/<string:track_rid>")
def showtrack(track_rid):
    """Shows track on the map."""
    # check if track_rid was provided and is an int, else flask sends 404
    if isinstance(track_rid, str):
        rid = uuid.UUID(track_rid)
        # check if track exist
        r1 = Trackz.query.filter_by(rid=rid).first()
        if r1:
            # get username of person who owns the track
            userdb = User.query.filter_by(id=r1.user_id).first_or_404()
            # get name of the track
            trackname = r1.name
            trackdesc = r1.description
            # check if track was rendered from a GPX and that GPX is private
            if r1.gpx_id:

motracker/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, Markup, current_app, render_template
from flask_login import login_required

from motracker.gpsdb.models import Trackz
from motracker.utils import track2svgpoints

from .models import User

blueprint = Blueprint("user", __name__, url_prefix="/users", static_folder="../static")


@blueprint.route("/")
@login_required
def members():
    """List members."""
    return render_template("users/members.html")


@blueprint.route("/<string:username>")
def userpage(username):
    """Shows a home page for a user."""
    q1 = User.query.filter_by(username=username).first_or_404()
    # find all tracks belonging to user
    q2 = Trackz.query.filter_by(user_id=q1.id).all()
    # check if user has not set privacy flag
    if not q1.is_private and q2:
        current_app.logger.debug(
            "Found {} tracks for user {}.".format(len(q2), username)
        )
        # get a SVG overview
        svgo = {}
        for x in q2:
            svgo[x.id] = Markup(track2svgpoints(x.id))

        return render_template(
            "users/showoff.html",
            firstname=q1.first_name,
            lastname=q1.last_name,
            username=username,
            trackz=q2,
            svgo=svgo,
        )
    else:  # page is private
        return render_template("404.html"), 404

motracker/templates/gpsdb/apikey.html
{% extends "layout.html" %}
{% block page_title %}Your personal API key(s) / moT{% endblock %}
{% block content %}
    <div class="container">
        <h1>{{ current_user.username }},</h1>
        <h3>your secret and unique API key(s):</h3>
        <div class="card-columns">
            {% for apikey in apikeys %}
            <div class="card border-primary mb-3" style="max-width: 20rem;">
                <div class="card-body">
                    <h4 class="card-title">{{ apikey }}</h4>
                </div>
                <div class="card-footer pull-right badge-pill badge-danger badge"><a href={{ url_for('gpsdb.rmapi', api=apikey) }}>remove forever</a></div>
            </div>
            {% endfor %}
            </div>
        <br/>
        <form id="ApiForm" class="form form-api" method="POST" action="" role="form">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.confirm.label }}
                {{ form.confirm }}
            </div>
            <p><input class="btn btn-primary" type="submit" value="Generate and add a new API key"></p>
        </form>
    </div>
{% endblock %}

motracker/templates/gpsdb/filez.html
{% extends "layout.html" %}
{% block page_title %}Your uploaded GPXs / moTracker{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <h1>{{ current_user.username }},</h1>
                <h3>it is file upload form.</h3>
            </div>
            <div class="col-sm-4">
                <form id="FileUpladForm" class="form form-file-upload" method="POST" action="" role="form" enctype="multipart/form-data">
                    {{ form.csrf_token }}
                    <div class="form-group">
                        {{ form.description.label }}
                        {{ form.description }}
                    </div>
                    <div class="form-group">
                        {{ form.is_private.label }}
                        {{ form.is_private }}
                    </div>
                    <div class="form-group">
                        {{ form.upload_file.label }}
                        {{ form.upload_file}}
                    </div>
                    <p><input class="btn btn-primary" type="submit" value="Upload"></p>
                </form>
            </div>
        </div>
        <div class="row">
            <table class="table table-striped table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">When uploaded?</th>
                        <th scope="col">Description</th>
                        <th scope="col">Content</th>
                        <th scope="col">Privacy</th>
                    </tr>
                </thead>
                <tbody>
                    {% for filename in allfilez|sort(attribute='id', reverse = True) %}
                    <tr>
                        <th scope="row">{{ filename.id }}.gpx <a href={{ url_for('gpsdb.gpxtrace', gpx_id=filename.id) }}><span class="badge badge-secondary">show</span></a></th>
                        <td>{{ filename.when_uploaded }}</td>
                        <td>{{ filename.description }}</td>
                        <td><small>{% for x in gpxq[filename.id] %} {{ x }}<br/> {% endfor %}</small></td>
                        <td>{{ filename.is_private }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

motracker/templates/gpsdb/realtime.html
{% extends "layout.html" %}
{% block page_title %}Track {{ track_rid }} map / moTracker{% endblock %}
{% block content %}
<script>
    var trackrid = "{{ track_rid }}";
    var realtime = 1;
</script>
    <div class="container-fluid">
        <ol class="breadcrumb bg-dark">
            <li class="breadcrumb-item active"><span class="badge badge-primary"><a href={{ url_for('user.userpage', username=username) }}>{{ username }}</a></span></li>
            <li id="name" class="breadcrumb-item"></li>
            <li class="breadcrumb-item">realtime</li>
            <li id="speed" class="breadcrumb-item"></li>
            <li id="altitude" class="breadcrumb-item"></li>
            <li id="satt" class="breadcrumb-item"></li>
            <li id="when" class="breadcrumb-item"></li>
        </ol>
        <div class="row">
            <div class="col-sm">
                <div id="gnssmap"></div>
            </div>
        </div>
    </div>
{% endblock %}
{% block footer %}{% endblock %}

motracker/templates/gpsdb/showtrack.html
{% extends "layout.html" %}
{% block page_title %}m⓿T / {{ track_rid }}{% endblock %}
{% block content %}
<script>
    var trackrid = "{{ track_rid }}";
</script>
    <div class="container-fluid">
        <ol class="breadcrumb bg-dark">
            <li class="breadcrumb-item active"><span class="badge badge-primary"><a href={{ url_for('user.userpage', username=username) }}>{{ username }}</a></span></li>
            <li class="breadcrumb-item">{{ track_rid }}</li>
            <li class="breadcrumb-item">{{ trackname }}</li>
            <li class="breadcrumb-item">{{ trackdesc }}</li>
            <li class="breadcrumb-item"><a href={{ url_for('gpsdb.geojson', track_rid=track_rid, limit='0' )}}>[GeoJSON]</a></li>
        </ol>
        <div class="row">
            <div class="col-sm">
                <div id="gnssmap"></div>
            </div>
        </div>
    </div>
{% endblock %}
{% block footer %}{% endblock %}