motracker/gpsdb/views.py
# -*- coding: utf-8 -*-
"""Gpsdb views."""

import binascii
import gpxpy
import json
import pynmea2
import re
import redis
import strgen
import uuid
from datetime import datetime, date
from flask import (
    Blueprint,
    current_app,
    flash,
    jsonify,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from flask_login import current_user, login_required
from flask_mail import Message
from sqlalchemy import text

# from motracker.extensions import celery, db, filez
from motracker.extensions import csrf_protect, db, mail
from motracker.user.models import User
from motracker.utils import flash_errors, gpx2geo

from .forms import AddFileForm, ApiForm
from .models import ApiKey, Filez, Pointz, Trackz

# SUPPORT FUNCTIONS and CONSTANTS
# -------------------------------


# fake track as default response
faketrack = '{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":\
        "LineString","coordinates":[[102.0, 0.0], [103.0, 1.0], [104.0, 0.0], [105.0, 1.0]]}}]}'

# $RMC
def parse_rmc(gprmc):
    """Parsing NMEA-0183 $RMC record into more human set of values.

    Recommended Minimum Specific GPS/TRANSIT Data:
    parser library: https://github.com/Knio/pynmea2
    """
    valuez = pynmea2.parse(gprmc)

    lat = valuez.latitude
    lon = valuez.longitude
    speed = valuez.spd_over_grnd
    bearing = valuez.true_course
    timez = datetime.combine(valuez.datestamp, valuez.timestamp)
    trackdate = valuez.datestamp

    return dict(
        timez=timez, lat=lat, lon=lon, speed=speed, bearing=bearing, trackdate=trackdate
    )


###########
# MAIN PART
blueprint = Blueprint("gpsdb", __name__, url_prefix="", static_folder="../static")


@blueprint.route("/apikeys", methods=["GET", "POST"])
@login_required
def gpsapi():
    """(re)Generate and/or present API key."""
    form = ApiForm(request.form)
    hasapi = ApiKey.query.filter_by(user_id=current_user.get_id()).all()
    # Handle regeneration of API key
    if request.method == "POST":
        if form.validate_on_submit():
            apikey = strgen.StringGenerator("[\w\d]{10}").render()
            ApiKey.create(user_id=current_user.get_id(), apikey=apikey)
            db.session.commit()
            current_app.logger.info("API key has been added.")
            flash("API key {} has been added.".format(apikey), "info")
            return redirect(url_for("gpsdb.gpsapi"))
        else:
            flash_errors(form)
    # No regeneration request
    apikey = []
    if hasapi:
        for x in hasapi:
            apikey.append(x.apikey)
    db.session.close()
    return render_template("gpsdb/apikey.html", form=form, apikeys=apikey)


@blueprint.route("/apikeys/rm/<string:api>", methods=["GET"])
@login_required
def rmapi(api):
    """RM api key. Everyone logged can remove a key if known."""
    hasapi = ApiKey.query.filter_by(apikey=api).first_or_404(description='There is no data with api key {}'.format(api))
    print(hasapi.apikey)
    db.session.delete(hasapi)
    db.session.commit()
    flash("API key {} has been removed.".format(hasapi.apikey), "warning")
    return redirect(url_for("gpsdb.gpsapi"))


@blueprint.route("/gnss/files", methods=["GET", "POST"])
@login_required
def filezsave():
    """Upload previously recorded tracks."""
    form = AddFileForm()
    if request.method == "POST":
        if form.validate_on_submit():
            # Verify if the GPX is valid
            file = request.files["upload_file"]
            try:
                # At the moment we support UTF-8 files and compatible only
                rid = uuid.uuid4()
                parsedfile = file.stream.read().decode("utf-8")
                ourgpx = gpxpy.parse(parsedfile)
                # file is parsing, so we are extracting basic interesting data about it
                length_2d = ourgpx.length_2d()
                length_3d = ourgpx.length_3d()
                moving_time, stopped_time, moving_distance, stopped_distance, max_speed = (
                    ourgpx.get_moving_data()
                )
                uphill, downhill = ourgpx.get_uphill_downhill()
                start_time, end_time = ourgpx.get_time_bounds()
                points_no = len(list(ourgpx.walk(only_points=True)))
            except Exception as e:
                current_app.logger.info(e)
                flash("Uploaded file is not a valid GPX. Try another one.", "warning")
                query = Filez.query.filter_by(user_id=current_user.get_id()).all()
                return render_template("gpsdb/filez.html", allfilez=query, form=form)
            dbfile = Filez.create(
                user_id=current_user.get_id(),
                is_private=form.is_private.data,
                rid=rid,
                description=form.description.data,
            )
            # all tracks are saved with filename which is equal to database ID
            fname = current_app.config["UPLOADS_DEFAULT_DEST"] + str(rid) + ".gpx"
            with open(fname, "w", encoding="utf-8") as f:
                f.write(parsedfile)
            fname = current_app.config["UPLOADS_DEFAULT_DEST"] + str(rid) + ".txt"
            with open(fname, "w", encoding="utf-8") as f:
                try:
                    f.write("Number of points: {}\n".format(points_no))
                except Exception as e:
                    current_app.logger.debug(e)
                try:
                    f.write("Start time: {}\n".format(start_time))
                except Exception as e:
                    current_app.logger.debug(e)
                try:
                    f.write("End time: {}\n".format(end_time))
                except Exception as e:
                    current_app.logger.debug(e)
                try:
                    f.write("2D length: {}\n".format(length_2d))
                except Exception as e:
                    current_app.logger.debug(e)
                try:
                    f.write("3D length: {}\n".format(length_3d))
                except Exception as e:
                    current_app.logger.debug(e)
                try:
                    f.write("Moving time: {}\n".format(moving_time))
                except Exception as e:
                    current_app.logger.debug(e)
                try:
                    f.write("Stopped time: {}\n".format(stopped_time))
                except Exception as e:
                    current_app.logger.debug(e)
                try:
                    f.write("Moving distance: {}\n".format(moving_distance))
                except Exception as e:
                    current_app.logger.debug(e)
                try:
                    f.write("Stopped distance: {}\n".format(stopped_distance))
                except Exception as e:
                    current_app.logger.debug(e)
                try:
                    f.write("Max speed: {}\n".format(max_speed))
                except Exception as e:
                    current_app.logger.debug(e)
                try:
                    f.write("Uphill: {}\n".format(uphill))
                except Exception as e:
                    current_app.logger.debug(e)
                try:
                    f.write("Downhill: {}\n".format(downhill))
                except Exception as e:
                    current_app.logger.debug(e)
            flash("Successfully uploaded your GPX file.", "info")
            current_app.logger.debug("Saved File: " + str(rid) + ".gpx")
        else:
            flash_errors(form)
    # Present all files belonging to user
    query = Filez.query.filter_by(user_id=current_user.get_id()).all()
    current_app.logger.debug(query)
    gpxq = {}
    for x in query:
        # A brief description presentation
        fname = current_app.config["UPLOADS_DEFAULT_DEST"] + str(x.rid) + ".txt"
        with open(fname, "r", encoding="utf-8") as f:
            read_file = f.readlines()
            gpxq[x.id] = read_file
    return render_template("gpsdb/filez.html", allfilez=query, gpxq=gpxq, form=form)


@blueprint.route("/gnss/gpx/<string:gpx_rid>")
def gpxtrace(gpx_rid):
    """Initiates convertion of GPX into our DB and redirects to show GPX on a map."""
    # TODO: use celery to parse the track
    # check if we have the GPS already rendered, if not, render it
    rid = uuid.UUID(gpx_rid)
    track = Trackz.query.filter_by(gpx_rid=rid).first()
    if not track:
        # get username current user
        track_rid = gpx2geo(rid)
    else:
        track_rid = track.rid
    return redirect(url_for("gpsdb.showtrack", track_rid=str(track_rid)))


@blueprint.route("/gnss/tracks/<string:username>")
def usertracks(username):
    """Lists all tracks for the particular user."""
    # check if username was provided and is valid, else flask sends 404.
    if isinstance(username, str):
        # check if user exists
        userdb = User.query.filter_by(username=username).first_or_404()
        user_id = userdb.id
        # we do not list GPX static files here, only live tracks
        q1 = Trackz.query.filter_by(id=user_id, gpx_id=None).all()
        if q1:
            current_app.logger.debug(q1)
            return render_template("gpsdb/alltracks,html", username=username)
        else:
            return render_template("404.html"), 404


@blueprint.route("/gnss/show/<string:track_rid>")
def showtrack(track_rid):
    """Shows track on the map."""
    # check if track_rid was provided and is an int, else flask sends 404
    if isinstance(track_rid, str):
        rid = uuid.UUID(track_rid)
        # check if track exist
        r1 = Trackz.query.filter_by(rid=rid).first()
        if r1:
            # get username of person who owns the track
            userdb = User.query.filter_by(id=r1.user_id).first_or_404()
            # get name of the track
            trackname = r1.name
            trackdesc = r1.description
            # check if track was rendered from a GPX and that GPX is private
            if r1.gpx_id:

motracker/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, Markup, current_app, render_template
from flask_login import login_required

from motracker.gpsdb.models import Trackz
from motracker.utils import track2svgpoints

from .models import User

blueprint = Blueprint("user", __name__, url_prefix="/users", static_folder="../static")


@blueprint.route("/")
@login_required
def members():
    """List members."""
    return render_template("users/members.html")


@blueprint.route("/<string:username>")
def userpage(username):
    """Shows a home page for a user."""
    q1 = User.query.filter_by(username=username).first_or_404()
    # find all tracks belonging to user
    q2 = Trackz.query.filter_by(user_id=q1.id).all()
    # check if user has not set privacy flag
    if not q1.is_private and q2:
        current_app.logger.debug(
            "Found {} tracks for user {}.".format(len(q2), username)
        )
        # get a SVG overview
        svgo = {}
        for x in q2:
            svgo[x.id] = Markup(track2svgpoints(x.id))

        return render_template(
            "users/showoff.html",
            firstname=q1.first_name,
            lastname=q1.last_name,
            username=username,
            trackz=q2,
            svgo=svgo,
        )
    else:  # page is private
        return render_template("404.html"), 404

motracker/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

motracker/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>© Dr. Serge Victor</li>
  </ul>
  <ul class="footer-nav">
    <li><a href="{{ url_for('public.about') }}">About</a></li>
    <li><a href="mailto:motracker@random.re">Contact</a></li>
  </ul>
  </small>
</footer>

motracker/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>{% block page_title %}Home / m◉T{% endblock %}
  </title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  {{ stylesheet_tag('main_css') | safe }}

  {% block css %}{% endblock %}

</head>
<body class="{% block body_class %}{% endblock %}">
{% block body %}
{% with form=form  %}
{% include "nav.html" %}
{% endwith %}

<header>{% block header %}{% endblock %}</header>

<main role="main">
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
        <div class="row">
          <div class="col-md-12">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
              <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
             {{message}}
            </div><!-- end .alert -->
            {% endfor %}
          </div><!-- end col-md -->
        </div><!-- end row -->
{% endif %}
{% endwith %}

{% block content %}{% endblock %}
</main>

<!-- footer -->
{% block footer %}
{% include "footer.html" %}
{% endblock %}

<!-- JavaScript at the bottom for fast page loading -->
{{ javascript_tag('main_js') | safe }}
{% block js %}{% endblock %}
<!-- end scripts -->
{% endblock %}
</body>
</html>

motracker/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <a class="navbar-brand" href="{{ url_for('public.home') }}">m◉T</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        {% if current_user and current_user.is_authenticated %}
          {% if current_user_live_track %}
          <a class="nav-link" href="{{ url_for('gpsdb.realtime', track_rid=current_user_live_track) }}"><span class="badge badge-danger badge-pill">LIVE!</span> </a> </li><li>
          {% endif %}
          <a class="nav-link" href="{{ url_for('user.userpage', username=current_user.username) }}"><span class="badge badge-secondary badge-pill">Your data</span>
        {% endif %}
          <span class="sr-only">(current)</span>
        </a>
      </li>
      {% if current_user and current_user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="gnssmenu">Menu <span class="caret"></span></a>
        <div class="dropdown-menu" aria-labelledby="gnssmenu">
            <a class="dropdown-item" href="{{ url_for('gpsdb.filezsave') }}">Uploaded GPXs</a>
            <a class="dropdown-item" href="{{ url_for('gpsdb.gpsapi') }}">API</a>
        </div>
      </li>
      {% endif %}
    </ul>
    {% if current_user and current_user.is_authenticated %}
    <ul class="navbar-nav my-auto">
      <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('user.userpage', username=current_user.username) }}"><i class="fa fa-user"></i> {{ current_user.username }}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('public.logout') }}">
          <i class="fa fa-sign-out"></i>
        </a>
      </li>
    </ul>
    {% elif form %}
    <form class="form-inline" id="loginForm" method="POST" action="/" role="login">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
      <div class="input-group mb-2 mr-sm-2">
        {{ form.username(placeholder="Username", class_="form-control mr-sm-1 my-auto") }} {{ form.password(placeholder="Password",
        class_="form-control mr-sm-1 my-auto") }}
        <button class="btn btn-light btn-primary m-auto" type="submit">Login</button>
      </div>
    </form>
    <ul class="navbar-nav my-auto">
      <li class="nav-item">
        <a class="nav-link navbar-text" href="{{ url_for('public.register') }}">Create account</a>
      </li>
    </ul>
    {% endif %}
  </div><!-- /.navbar-collapse -->
</nav>